version: '2'

services:
  db:
    image: jsurf/rpi-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_USER: your_mysql_username
      MYSQL_PASSWORD: your_mysql_password
      MYSQL_DATABASE: schedulecast
      PUID: 1000
      PGID: 1000
    volumes:
      - /home/pi/schedule-cast/db:/var/lib/mysql
      - /home/pi/schedule-cast/init.db:/docker-entrypoint-initdb.d

  web:
    image: webhippie/php-apache
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: schedulecast
      FR_DB_USER: your_mysql_username
      FR_DB_PASS: your_mysql_password
      APACHE_RUN_USER: pi
      APACHE_RUN_USER_ID: 1000
      APACHE_RUN_GROUP: pi
      APACHE_RUN_GROUP_ID: 1000
      PHP_DATE_TIMEZONE: America/Los_Angeles

    depends_on:
      - db
    links:
      - db:db
    ports:
      - "8080:8080"
    volumes:
      - /home/pi/schedule-cast/html:/srv/www

# May need a db maintainer container
#  maint:
#    image: mfederw/schedulecast_maint
